name: Roger Greer Insurance
favicon: null
layout_spectrum: 0.9391485534142703
typography_spectrum: 0.2543503805063665
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9766629594378173
  lightness: 0.4704166352748871
  saturation: 0.13287221151404083
  rhythmicContrast: 0.8504517492838204
purpose: []
